### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [gaokohl/Dasmoto-project#6]
https://github.com/gaokohl/Dasmoto-project/blob/master/resources/style.css#L9

Avoid the repetitive process of listing additional elements here and ensure the style gets applied by putting it in a more general selector like `*`.

```css
* {
  font-family: Helvetica;
}
```
